# Generated by Django 5.1.6 on 2025-04-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0002_detection_accuracy_detection_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation_attack_detection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Remote_User.clientregister_model'),
        ),
    ]
